import { ArrowRight, Building2, CheckCircle2, Package, Plus, Store } from "lucide-react";
import { Link } from "react-router-dom";
import VendorShell, { AddListingButton } from "../components/VendorShell";
import { readSessionCache } from "../api/portal";

interface VendorProfile { business_name?: string; about?: string; district?: string; areas_served?: string[]; offer?: string[]; }

export default function VendorDashboard() {
  const profile = readSessionCache<VendorProfile>("vendorProfile") || {};
  const businessName = profile.business_name || sessionStorage.getItem("userName") || "Your shop";
  const completed = [profile.business_name, profile.about, profile.district, profile.areas_served?.length, profile.offer?.length].filter(Boolean).length;
  const completion = Math.round((completed / 5) * 100);
  return <VendorShell><div className="mx-auto max-w-[1300px] px-4 py-6 sm:px-8 sm:py-9 xl:px-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Business workspace</p><h1 className="page-title mt-2">Welcome, {businessName}</h1><p className="mt-2 text-sm text-muted-foreground sm:text-base">Manage your shop profile and bridal listings from here.</p></div><AddListingButton/></header><section className="mt-8 grid gap-4 md:grid-cols-3"><Summary icon={<CheckCircle2/>} label="Profile completion" value={`${completion}%`} note="Keep your shop information current"/><Summary icon={<Package/>} label="My Listings" value="0" note="Listings will appear here"/><Summary icon={<Store/>} label="Vendor Profile" value={profile.district || "Ready"} note="Your public business presence"/></section><section className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="surface-card p-6 sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-accent text-primary"><Plus/></span><h2 className="display-font mt-5 text-2xl font-bold">Add your first listing</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Your product tools will connect here as the vendor catalogue is enabled. The route is ready for the next integration step.</p><Link to="/vendor/products" className="secondary-button mt-6">Open My Listings <ArrowRight size={17}/></Link></div><div className="rounded-2xl bg-[#321a27] p-6 text-white sm:p-8"><Building2 className="text-[#d5b466]"/><h2 className="display-font mt-5 text-2xl font-bold">Build trust with brides</h2><p className="mt-3 text-sm leading-6 text-white/60">Complete your business story, service areas and bridal specialties.</p><Link to="/vendor/profile" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#e0c680]">View Vendor Profile <ArrowRight size={17}/></Link></div></section></div></VendorShell>;
}

function Summary({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: string; note: string }) { return <article className="surface-card p-5 sm:p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-primary [&>svg]:h-5 [&>svg]:w-5">{icon}</span><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></article>; }
